# Generated by Django 3.2.9 on 2021-11-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListItem',
            new_name='List',
        ),
    ]
