name: Building and testing
on:
  push:
    branches: [main]
jobs:
  build-react:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - run: npm run build --if-present
      - run: npm test
      - name: Uploading built frontend app
        uses: actions/upload-artifact@v2
        with:
          name: frontend-built
          path: ./client/static/client/main.js
  build-django:
    runs-on: ubuntu-latest
    needs: build-react
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev -y
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install python3-distutils
          pip install -r requirements.txt
      - name: Download built frontend
        uses: actions/download-artifact@v2
        with:
          name: frontend-built
          path: ./client/static/client/main.js
      - name: Run Django Tests
        run: |
          python manage.py test server/unittests
#  heroku-deploy:
#    runs-on: ubuntu-latest
#    name: Git Deploy job- A job to deploy django app to heroku using git
#    needs: build-react
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Download built frontend
#        uses: actions/download-artifact@v2
#        with:
#          name: frontend-built
#          path: ./client/static/client/main.js
#      - name: Deploy django to heroku
#        uses: akhileshns/heroku-deploy@v3.12.12
#        with:
#          heroku_app_name : ${{ secrets.HEROKU_APP_NAME }}
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_email: 'morzharetto@icloud.com'
#          branch: "main"
