  name: Running tests
  on:
    push:
      branches: [main]
  jobs:
    build-react:
      runs-on: ubuntu-latest
      env:
        working-directory: ./client
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - name: Install dependencies
          run: npm install
        - run: npm run build --if-present
        - run: npm test
    build-django:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run Django Tests
          run: |
            python manage.py test
