name: Building and testing
on:
  push:
    branches: [main]
jobs:
  build-react:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - run: npm run build --if-present
      - run: npm test
      - name: Uploading built frontend app
        uses: actions/upload-artifact@v2
        with:
          name: frontend-built
          path: static/client/main.js
  build-django:
    runs-on: ubuntu-latest
    needs: build-react
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download built frontend
        uses: actions/download-artifact@v2
        with:
          name: docker-frontend-built
          path: client/static/client/main.js
      - name: Run Django Tests
        run: |
          python manage.py test server/unittests
